"""add note_yet_created_date

Revision ID: 3465f5f5fbfd
Revises: c9eddf898fba
Create Date: 2019-01-09 00:43:56.167005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3465f5f5fbfd'
down_revision = 'c9eddf898fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_yet', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_yet', 'created_date')
    # ### end Alembic commands ###
