"""add status in Note

Revision ID: bdc05b06a42b
Revises: aa88049d5cd8
Create Date: 2019-01-29 14:40:16.612074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc05b06a42b'
down_revision = 'aa88049d5cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'status')
    # ### end Alembic commands ###
