"""add Note_yet admin id

Revision ID: c9eddf898fba
Revises: 9a861a3c2569
Create Date: 2019-01-07 22:14:29.224960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9eddf898fba'
down_revision = '9a861a3c2569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_yet', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note_yet', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note_yet', type_='foreignkey')
    op.drop_column('note_yet', 'admin_id')
    # ### end Alembic commands ###
